### ISSUE TITLE
remove comma (causing php error)

### ISSUE THREAD

**Issue by M-Diais** [rankmath/seo-by-rank-math#41] opened 2020-12-08 15:50 UTC
https://github.com/rankmath/seo-by-rank-math/blob/f1907489a973d7dc42dc94fcb6b0949f5a08fec6/includes/admin/class-serp-preview.php#L460

**Comment by surajv** [comment] 2020-12-08 16:01
Duplicate of https://github.com/rankmath/seo-by-rank-math/issues/43

**Closed by surajv** 2020-12-08 16:01 UTC
Labels: duplicate
